remove homebrew/services
apparently it is deprecated. saw this error while running the script:


```
Tapping homebrew/services has failed!
Error: homebrew/services was deprecated. This tap is now empty and all its contents were either deleted or migrated.
```